name: Test CI

on:
 push:
  branches:
   - master
 pull_request:
  branches:
   - master

env:
 CSV_URL: "MLProject/cuacaAustralia_preprocessing.csv"
 TARGET_VAR: "RainTomorrow"

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
   # Checks-out your repository under $GITHUB_WORKSPACE
   - uses: actions/checkout@v3

   # Setup Python 3.13.13
   - name: Set up Python 3.13.13
     uses: actions/setup-python@v3
     with:
      python-version: "3.13.13"
  
   # Check Env Variables
   - name: Check Env
     run: |
      echo $CSV_URL

   # ADD THIS STEP - Pull Git LFS files
   - name: Checkout LFS objects
     run: |
       git lfs install
       git lfs pull

   # Install mlflow
   - name: Install dependencies
     run: |
      python -m pip install --upgrade pip
      pip install mlflow
  
   # Run as a mlflow project
   - name: Run mlflow project
     run: |
      mlflow run MLProject --env-manager=local

   # mencari run_id terbaru dari direktori mlruns/0/ dan menyimpannya sebagai variabel lingkungan baru bernama RUN_ID
   - name: Get latest MLflow run_id
     run: |
       RUN_ID=$(ls -td mlruns/0/models/*/ | head -n 1 | cut -d'/' -f4)
       echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
       echo "Latest run_id: $RUN_ID"

   # memastikan model yang telah dilatih dapat dikemas dalam container yang siap untuk diterapkan
   - name: Build Docker Model
     run: |
       mlflow models build-docker --model-uri "mlruns/0/models/$RUN_ID/artifacts/" --name "tes_docker"

   # akses untuk mengelola repositori Docker
   - name: Log in to Docker Hub
     uses: docker/login-action@v2
     with:
       username: ${{ secrets.DOCKER_HUB_USERNAME }}
       password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

   # menandai image Docker yang telah dibuat agar sesuai dengan nama pengguna Docker Hub
   - name: Tag Docker Image
     run: |
       docker tag tes_docker ${{ secrets.DOCKER_HUB_USERNAME }}/tes_docker:latest

   # mengunggah image Docker ke Docker Hub
   - name: Push Docker Image
     run: |
       docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cc:latest

   # - name: Set up Git LFS
   #   run: |
   #     git config --global user.name ${{ secrets.USERNAME }}
   #     git config --global user.email ${{ secrets.EMAIL }}
   #     git lfs install
   #     git lfs track "mlruns/**"
   #     git add .gitattributes
   #     git commit -m "Track large files in mlruns with Git LFS" || true
   #     git pull origin master --rebase || true
   #     git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git master || true

   # - name: Save mlruns to repo
   #   run: |
   #     git config --global user.name ${{ secrets.USERNAME }}
   #     git config --global user.email ${{ secrets.EMAIL }}
   #     git add -f mlruns/
   #     git commit -m "Save mlruns from CI run" || true
   #     git pull origin master --rebase || true
   #     git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git master || true
