name: Test CI

on:
 push:
  branches:
   - master
 pull_request:
  branches:
   - master

env:
 CSV_URL: "MLProject/cuacaAustralia_preprocessing.csv"

jobs:
 build:
  runs-on: ubuntu-latest

  steps:
   # Checks-out your repository under $GITHUB_WORKSPACE
   - uses: actions/checkout@v3

   # Setup Python 3.13.13
   - name: Set up Python 3.13.13
     uses: actions/setup-python@v4
     with:
      python-version: "3.13.13"
  
   # Check Env Variables
   - name: Check Env
     run: |
      echo $CSV_URL

   # ADD THIS STEP - Pull Git LFS files
   - name: Checkout LFS objects
     run: |
       git lfs install
       git lfs pull

   # Install mlflow
   - name: Install dependencies
     run: |
      python -m pip install --upgrade pip
      pip install mlflow
  
   # Run as a mlflow project
   - name: Run mlflow project
     run: |
      mlflow run MLProject --env-manager=local

   - name: Set up Git LFS
     run: |
       git config --global user.name ${{ secrets.USERNAME }}
       git config --global user.email ${{ secrets.EMAIL }}
       git lfs install
       git lfs track "mlruns/**"
       git add .gitattributes
       git commit -m "Track large files in mlruns with Git LFS" || true
       git pull origin master --rebase || true
       git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git master || true

   - name: Save mlruns to repo
     run: |
       git config --global user.name ${{ secrets.USERNAME }}
       git config --global user.email ${{ secrets.EMAIL }}
       git add -f mlruns/
       git commit -m "Save mlruns from CI run" || true
       git pull origin master --rebase || true
       git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git master || true
